In [1]:
import open3d as o3d
import numpy as np

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


## Point Cloud를 읽어서 화면에 표시

print("Load a ply point cloud, print it, and render it")
ply_point_cloud = o3d.data.PLYPointCloud()   #샘플 데이터

# Point cloud 읽기
pcd = o3d.io.read_point_cloud(ply_point_cloud.path)
# read_point_cloud() - PLY 파일을 PointCloud 객체로 변환해줌 

print(pcd) 
print(np.asarray(pcd.points)) # 점들의 좌표 보기

# 시각화 
o3d.visualization.draw_geometries([pcd],
                                  zoom=0.3412,
                                  front=[0.4257, -0.2125, -0.8795],
                                  lookat=[2.6172, 2.0475, 1.532],
                                  up=[-0.0694, -0.9768, 0.2024])

## Downsampling
-> 데이터의 해상도나 샘플링 속도를 낮춰 데이터의 전체 크기(or 샘플 수)를 줄이는 데이터 처리 기술  
원본 Point Cloud에는 점이 너무 많음  
2D는 픽셀로 화면을 나눈다면  
3D는 Voxel로 작은 큐브처럼 나눈다   

In [3]:
print("Downsample the point cloud with a voxel of 0.05")
downpcd = pcd.voxel_down_sample(voxel_size=0.05)   #한 변의 길이가 0.05인 큐브를 만든다 
o3d.visualization.draw_geometries([downpcd],
                                  zoom=0.3412,
                                  front=[0.4257, -0.2125, -0.8795],
                                  lookat=[2.6172, 2.0475, 1.532],
                                  up=[-0.0694, -0.9768, 0.2024])

Downsample the point cloud with a voxel of 0.05


## 법선 계산
Normal : 법선 - 표면에 수직인 방향을 나타내는 벡터   
자동으로 길이는 1이되도록 정규화

In [ ]:
print("Recompute the normal of the downsampled point cloud")
downpcd.estimate_normals(     #estimate_normals()을 실행하면 법선 벡터가 추가됨 
    search_param=o3d.geometry.KDTreeSearchParamHybrid(radius=0.1, max_nn=30))
o3d.visualization.draw_geometries([downpcd],
                                  zoom=0.3412,
                                  front=[0.4257, -0.2125, -0.8795],
                                  lookat=[2.6172, 2.0475, 1.532],
                                  up=[-0.0694, -0.9768, 0.2024],
                                  point_show_normal=True)

## Normal 사용
0번째 법선 벡터   
0~9번째 법선 벡터

In [10]:
print("Print a normal vector of the 0th point")
print(downpcd.normals[0])

Print a normal vector of the 0th point
[ 0.89445022  0.02628609 -0.15662958]


In [11]:
print("Print the normal vectors of the first 10 points")
print(np.asarray(downpcd.normals)[:10, :])

Print the normal vectors of the first 10 points
[[ 8.94450224e-01  2.62860943e-02 -1.56629584e-01]
 [-3.13758548e-01  3.55896414e-02 -9.44423441e-01]
 [-1.47776814e-01  6.17785521e-02 -9.19603061e-01]
 [-5.09037352e-01 -2.12256503e-01 -7.93828250e-01]
 [-2.65132504e-01  1.45827847e-02 -9.55608159e-01]
 [-2.99585901e-02 -9.84751935e-01 -6.62941613e-03]
 [ 8.94761360e-01 -6.20907552e-02  3.21312763e-01]
 [ 7.64649808e-01  6.31591329e-02  5.80496031e-01]
 [-3.03514555e-03 -9.98822002e-01 -2.93296441e-02]
 [-2.83795584e-01  1.87381510e-05 -9.48635019e-01]]
